// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.Models;

namespace Persistence.Migrations
{
    [DbContext(typeof(ConditionHandlerContext))]
    [Migration("20200215204412_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Persistence.Models.Condition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConditionName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ConditionPropertyValue")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<int?>("ConditionSetId")
                        .HasColumnType("int");

                    b.Property<string>("ConditionValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PropertyName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.HasIndex("ConditionSetId");

                    b.ToTable("Condition");
                });

            modelBuilder.Entity("Persistence.Models.ConditionActions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActionName")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("ActionParameterValues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CronExpression")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MasterConditionSetId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int?>("RetryCount")
                        .HasColumnType("int");

                    b.Property<bool?>("StopOnException")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("MasterConditionSetId");

                    b.ToTable("ConditionAction");
                });

            modelBuilder.Entity("Persistence.Models.ConditionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MasterConditionSetId")
                        .HasColumnName("MasterConditionISetd")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MasterConditionSetId");

                    b.ToTable("ConditionSet");
                });

            modelBuilder.Entity("Persistence.Models.MasterConditionSet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("Id");

                    b.ToTable("MasterConditionSet");
                });

            modelBuilder.Entity("Persistence.Models.Condition", b =>
                {
                    b.HasOne("Persistence.Models.ConditionSet", "ConditionSet")
                        .WithMany("Conditions")
                        .HasForeignKey("ConditionSetId")
                        .HasConstraintName("FK_Conditions_ConditionSet1");
                });

            modelBuilder.Entity("Persistence.Models.ConditionActions", b =>
                {
                    b.HasOne("Persistence.Models.MasterConditionSet", "MasterConditionSet")
                        .WithMany("ConditionActions")
                        .HasForeignKey("MasterConditionSetId")
                        .HasConstraintName("FK_ConditionActions_MasterConditionSet");
                });

            modelBuilder.Entity("Persistence.Models.ConditionSet", b =>
                {
                    b.HasOne("Persistence.Models.MasterConditionSet", "MasterConditionSet")
                        .WithMany("ConditionSet")
                        .HasForeignKey("MasterConditionSetId")
                        .HasConstraintName("FK_ConditionSet_MasterConditionSet");
                });
#pragma warning restore 612, 618
        }
    }
}
